IAC-713 Doesn't Ask for All Required Information about importing vRА
vmware/build-tools-for-vmware-aria pull request #15
Opened 2023-02-06 17:02 UTC by marianmarinov

### Description

Installer v 2.27.0 Doesn't Ask for All Required Information about importing vRА.
Shows a prompt to ask for additional information for importing vRA - project name and ID and Organization name and ID.

### Checklist

- [x] Lint and unit tests pass locally with my changes
- [] I have added relevant error handling and logging messages to help troubleshooting
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have updated CHANGELOG.md with a short summary of the changes introduced
- [x] I have tested against live environment, if applicable
- [ ] I have added relevant usage information (As-built)
- [ ] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [ ] Every new or updated Installer property is documented in docs/archive/doc/markdown/use-bundle-installer.md
- [ ] Dependencies in pom.xml are up-to-date
- [ ] My changes have been rebased and squashed to the minimal number of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

### Release Notes

### Related issues and PRs

2023-02-08 09:35 UTC, Michaelpalacce commented
Please also add an entry to "Release.md"

2023-02-08 09:47 UTC, Michaelpalacce commented on package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java
> +        if (input.anyTrue(Option.VRANG_IMPORT, Option.CS_IMPORT)) {
Lets take a look at: https://jira.pscoe.vmware.com/browse/IAC-584 first. 

I think we may need to extract readVrangProperties(input); from this if else and leave it as is

2023-02-08 09:47 UTC, Michaelpalacce requested changes
Lets make sure we don't re-introduce a previous issue

2023-02-08 11:00 UTC, Michaelpalacce commented
Please include what exactly is missing, which options?

2023-02-08 12:00 UTC, marianmarinov commented
> 

The prompt for "Project name:" is missing and entire section of vRA questions (Project ID, Organization Name, Organization ID ...)

2023-02-09 08:34 UTC, Michaelpalacce approved these changes

2023-02-09 08:41 UTC, Michaelpalacce requested changes
Release.md

2023-02-09 09:57 UTC, marianmarinov commented
> Please also add an entry to "Release.md"

Done

2023-02-14 12:56 UTC, Michaelpalacce commented on docs/versions/latest/Release.md
> +#### Previous Behavior
Previous and new behavior in the form of:

"It wasn't working"

"now it's working"

doesn't give us any good information as to "why it wasn't working" and "how was it fixed"

2023-02-14 14:43 UTC, merged