Fix for issue 146 - pull not working on windows
vmware/build-tools-for-vmware-aria pull request #151
Opened 2023-07-13 10:27 UTC by krasimirr

### Description

### Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have updated CHANGELOG.md with a short summary of the changes introduced
- [x] I have tested against live environment, if applicable
- [ ] I have added relevant usage information (As-built)
- [ ] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [ ] Every new or updated Installer property is documented in docs/archive/doc/markdown/use-bundle-installer.md
- [x] Dependencies in pom.xml are up-to-date
- [x] My changes have been rebased and squashed to the minimal number of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

### Release Notes

Pull operation was failing on Windows for abx, ssh, vra-ng, vra, vrli.
Whenever a pull was initiated, it was failing with:

pull failed: 'posix:permissions' not supported as initial attribute

when trying to create a temporary directory.
This is due to PosixPermissions which can be used only with POSIX compatible operating systems.
This fix uses another library for temp dir creation which checks if POSIX is supported

### Related issues and PRs

2023-07-13 10:31 UTC, Michaelpalacce requested changes
Great job :) Only 1 comment.. waiting for tests

2023-07-13 10:31 UTC, Michaelpalacce commented on CHANGELOG.md
> +## v2.34.1 - 14 Jul 2023
No need to add tihs

2023-07-13 10:39 UTC, krasimirr commented on CHANGELOG.md
> +## v2.34.1 - 14 Jul 2023
Removed

2023-07-20 14:31 UTC, Michaelpalacce approved these changes

2023-07-20 14:34 UTC, merged