IAC-789 new Aria Auto vRO Plugin  inventory Types
vmware/build-tools-for-vmware-aria pull request #177
Opened 2023-10-26 12:37 UTC by vhagar91

### Description
Adding vro types related to the new Aria Automation 8.x vRO plugin 

### Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added relevant error handling and logging messages to help troubleshooting
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have updated CHANGELOG.md with a short summary of the changes introduced
- [x] I have tested against live environment, if applicable
- [x] I have added relevant usage information (As-built)
- [x] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [x] Every new or updated Installer property is documented in docs/archive/doc/markdown/use-bundle-installer.md
- [x] Dependencies in pom.xml are up-to-date
- [x] My changes have been rebased and squashed to the minimal number of relevant commits
- [ ] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Release Notes
[vro-types/o11n-plugin-aria] IAC-789 / Adding new Aria Automation Plugin vRO inventory Types

2023-10-26 13:06 UTC, Michaelpalacce requested changes
Lets update the Release.md file as well. Otherwise, great job!

2023-11-14 13:49 UTC, VenelinBakalov approved these changes

2023-11-14 14:11 UTC, VenelinBakalov approved these changes

2023-11-14 15:12 UTC, n-vodenicharski approved these changes

2023-11-14 15:15 UTC, merged