Origin/iac 591 vro backup
vmware/build-tools-for-vmware-aria pull request #75
Opened 2023-04-13 14:49 UTC by imihov1988

### Description

### Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added relevant error handling and logging messages to help troubleshooting
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have updated CHANGELOG.md with a short summary of the changes introduced
- [x] I have tested against live environment, if applicable
- [x] I have added relevant usage information (As-built)
- [x] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [x] Every new or updated Installer property is documented in docs/archive/doc/markdown/use-bundle-installer.md
- [x] Dependencies in pom.xml are up-to-date
- [x] My changes have been rebased and squashed to the minimal number of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

### Release Notes

### Related issues and PRs

2023-04-24 17:40 UTC, ivo-kotev requested changes
Please check the comments, they are very small and mostly related to the documentation and the  installer question, let's address them and we are ready to merge.

2023-04-26 09:00 UTC, imihov1988 commented on package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java
> +                    .importAllPackages(getFilesystemPackages(PackageType.BASIC), false, vroEnableBackup);
On line 570 I set the variable vroEnableBackup to false after using the variable in the vRO logic, decided better to pass it with a variable.

2023-04-26 09:06 UTC, imihov1988 commented on package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java
> +				userInput(input, Option.VRO_ENABLE_BACKUP, "Enable vRO backup?", true);
Addressed

2023-04-26 09:07 UTC, imihov1988 commented on docs/versions/latest/Release.md
> +[//]: # (### Implemented vRO backup during packages import)
Addressed

2023-04-26 16:08 UTC, merged